# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sybil.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsybil.proto\"Z\n\x0bScalarValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x42\x07\n\x05value\"/\n\x0fScalarValueList\x12\x1c\n\x06values\x18\x01 \x03(\x0b\x32\x0c.ScalarValue\")\n\nParameters\x12\x1b\n\x0b\x62\x61se_models\x18\x01 \x03(\x0b\x32\x06.Model\"C\n\x05Model\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07scorers\x18\x02 \x03(\t\x12\x1b\n\x06params\x18\x03 \x01(\x0b\x32\x0b.Parameters\"S\n\x0cTrainRequest\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.ScalarValueList\x12\x15\n\x05model\x18\x02 \x01(\x0b\x32\x06.Model\x12\x0c\n\x04json\x18\x03 \x01(\t\"%\n\x06Metric\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"F\n\rTrainResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x18\n\x07metrics\x18\x03 \x03(\x0b\x32\x07.Metric\"N\n\x0f\x46orecastRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.ScalarValueList\x12\x0c\n\x04json\x18\x03 \x01(\t\"2\n\x10\x46orecastResponse\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.ScalarValueList2`\n\x05Sybil\x12&\n\x05Train\x12\r.TrainRequest\x1a\x0e.TrainResponse\x12/\n\x08\x46orecast\x12\x10.ForecastRequest\x1a\x11.ForecastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sybil_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCALARVALUE']._serialized_start=15
  _globals['_SCALARVALUE']._serialized_end=105
  _globals['_SCALARVALUELIST']._serialized_start=107
  _globals['_SCALARVALUELIST']._serialized_end=154
  _globals['_PARAMETERS']._serialized_start=156
  _globals['_PARAMETERS']._serialized_end=197
  _globals['_MODEL']._serialized_start=199
  _globals['_MODEL']._serialized_end=266
  _globals['_TRAINREQUEST']._serialized_start=268
  _globals['_TRAINREQUEST']._serialized_end=351
  _globals['_METRIC']._serialized_start=353
  _globals['_METRIC']._serialized_end=390
  _globals['_TRAINRESPONSE']._serialized_start=392
  _globals['_TRAINRESPONSE']._serialized_end=462
  _globals['_FORECASTREQUEST']._serialized_start=464
  _globals['_FORECASTREQUEST']._serialized_end=542
  _globals['_FORECASTRESPONSE']._serialized_start=544
  _globals['_FORECASTRESPONSE']._serialized_end=594
  _globals['_SYBIL']._serialized_start=596
  _globals['_SYBIL']._serialized_end=692
# @@protoc_insertion_point(module_scope)
